services:
  - type: web
    name: directus-cms
    env: docker
    plan: free
    autoDeploy: true
    envVars:
      - key: KEY
        value: supersecretkey
      - key: ADMIN_EMAIL
        value: admin@example.com
      - key: ADMIN_PASSWORD
        value: strongpassword
      - key: DB_CLIENT
        value: pg
      - key: DB_HOST
        value: db
      - key: DB_PORT
        value: 5432
      - key: DB_DATABASE
        value: directus
      - key: DB_USER
        value: directus
      - key: DB_PASSWORD
        value: directus