services:
  - type: web
    name: directus
    env: docker
    plan: free
    autoDeploy: true
    dockerfilePath: ./Dockerfile
    envVars:
      - key: KEY
        value: supersecretkey
      - key: ADMIN_EMAIL
        value: admin@example.com
      - key: ADMIN_PASSWORD
        value: strongpassword
      - key: DB_CLIENT
        value: pg
      - key: DB_URL
        value: postgresql://neondb_owner:npg_mGO7Ceyk6AlR@ep-royal-shadow-abhuk4sw-pooler.eu-west-2.aws.neon.tech/directus?sslmode=require
