services:
  - type: web
    name: directus
    env: docker
    plan: starter
    autoDeploy: true

    disk:
      name: directus-data
      mountPath: /directus/uploads
      sizeGB: 1

    envVars:
      - key: ADMIN_EMAIL
        fromDatabase: ADMIN_EMAIL
      - key: ADMIN_PASSWORD
        fromDatabase: ADMIN_PASSWORD
      - key: DB_CLIENT
        value: pg
      - key: DB_HOST
        fromDatabase: DB_HOST
      - key: DB_PORT
        value: 5432
      - key: DB_DATABASE
        fromDatabase: DB_DATABASE
      - key: DB_USER
        fromDatabase: DB_USER
      - key: DB_PASSWORD
        fromDatabase: DB_PASSWORD
      - key: PGSSLMODE
        value: require
      - key: KEY
        fromDatabase: SECRET_KEY
