services:
  - type: web
    name: directus
    env: docker
    plan: free
    autoDeploy: true
    dockerfilePath: ./Dockerfile
    envVars:
      - key: KEY
        value: supersecretkey
      - key: ADMIN_EMAIL
        value: admin@example.com
      - key: ADMIN_PASSWORD
        value: strongpassword

      - key: DB_CLIENT
        value: pg
      - key: DB_HOST
        value: ep-royal-shadow-abhuk4sw-pooler.eu-west-2.aws.neon.tech
      - key: DB_PORT
        value: 5432
      - key: DB_DATABASE
        value: directus
      - key: DB_USER
        value: neondb_owner
      - key: DB_PASSWORD
        value: npg_mGO7Ceyk6AlR

      - key: PGSSLMODE
        value: require
